#!/bin/sh

set -e

if [ ! -f /etc/lsb_release ] && [ ! -f /etc/debian_version ]
then
    echo "Script is meant to install packages on Debian/Ubuntu based distributions"
    echo "Please install dependencies manually on other distributions"
    exit 1
fi

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install \
    build-essential texinfo curl file autoconf automake \
    flex bison zip \
    gcc-mingw-w64 g++-mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev \
    git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build \
    python3-pip python3 python3-devel texinfo

# Make sure MingGW compiler uses Posix threads
update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

# Ubuntu meson version is too old for QEMU
if grep "Ubuntu 22.04" /etc/lsb-release > /dev/null; then
    pip_cmd="pip3 install"
else
    pip_cmd="pip3 install --break-system-packages"
fi

$pip_cmd meson==1.4.0
